export const HUB_NAMES = {
  action: 'Action',
  adventure: 'Adventure',
  arcade: 'Arcade',
  puzzle: 'Puzzle',
  'brain-memory': 'Brain & Memory',
  'match-3': 'Match-3',
  casual: 'Casual',
  shooting: 'Shooting',
  'racing-driving': 'Racing & Driving',
  sports: 'Sports',
  strategy: 'Strategy',
  'board-card': 'Board & Card',
  'two-player': 'Two-Player',
  'girls-dress-up': 'Girls & Dress-up',
  'coloring-drawing': 'Coloring & Drawing',
  'simulation-idle': 'Simulation & Idle',
  platformer: 'Platformer',
  'skill-hyper-casual': 'Skill & Hyper-casual',
  'math-word': 'Math & Word',
  seasonal: 'Seasonal',
} as const;

export type HubSlug = keyof typeof HUB_NAMES;

export const HUB_SLUGS = Object.keys(HUB_NAMES) as HubSlug[];

/**
 * Every raw GamePix category maps to one hub. Brand categories stay mapped
 * so the feed can grow, and curation removes those games from pages.
 */
export const RAW_CATEGORY_TO_HUB = {
  '2048': 'arcade',
  action: 'action',
  addictive: 'arcade',
  adventure: 'adventure',
  airplane: 'racing-driving',
  animal: 'casual',
  anime: 'casual',
  arcade: 'arcade',
  archery: 'sports',
  ball: 'arcade',
  baseball: 'sports',
  basketball: 'sports',
  battle: 'action',
  'battle-royale': 'action',
  bejeweled: 'match-3',
  bike: 'racing-driving',
  block: 'puzzle',
  board: 'board-card',
  bowling: 'sports',
  boxing: 'sports',
  brain: 'brain-memory',
  'bubble-shooter': 'casual',
  building: 'simulation-idle',
  car: 'racing-driving',
  card: 'board-card',
  casual: 'casual',
  cats: 'casual',
  checkers: 'board-card',
  chess: 'board-card',
  christmas: 'seasonal',
  'city-building': 'simulation-idle',
  classics: 'arcade',
  clicker: 'skill-hyper-casual',
  coco: 'casual',
  coding: 'brain-memory',
  coloring: 'coloring-drawing',
  cooking: 'simulation-idle',
  cool: 'casual',
  crazy: 'arcade',
  cricket: 'sports',
  dinosaur: 'casual',
  'dirt-bike': 'racing-driving',
  dragons: 'adventure',
  drawing: 'coloring-drawing',
  'dress-up': 'girls-dress-up',
  drifting: 'racing-driving',
  driving: 'racing-driving',
  educational: 'brain-memory',
  escape: 'puzzle',
  family: 'casual',
  farming: 'simulation-idle',
  fashion: 'girls-dress-up',
  fighting: 'action',
  'fire-and-water': 'platformer',
  'first-person-shooter': 'shooting',
  fishing: 'simulation-idle',
  flash: 'arcade',
  flight: 'racing-driving',
  fun: 'casual',
  'games-for-girls': 'girls-dress-up',
  gangster: 'action',
  gdevelop: 'skill-hyper-casual',
  golf: 'sports',
  granny: 'adventure',
  gun: 'shooting',
  'hair-salon': 'girls-dress-up',
  halloween: 'seasonal',
  helicopter: 'racing-driving',
  'hidden-object': 'puzzle',
  hockey: 'sports',
  horror: 'action',
  horse: 'casual',
  hunting: 'shooting',
  'hyper-casual': 'skill-hyper-casual',
  idle: 'simulation-idle',
  io: 'arcade',
  jewel: 'match-3',
  'jigsaw-puzzles': 'puzzle',
  jumping: 'platformer',
  knight: 'action',
  mahjong: 'board-card',
  makeup: 'girls-dress-up',
  management: 'simulation-idle',
  mario: 'platformer',
  'match-3': 'match-3',
  math: 'math-word',
  memory: 'brain-memory',
  minecraft: 'adventure',
  mining: 'simulation-idle',
  mmorpg: 'adventure',
  mobile: 'casual',
  money: 'simulation-idle',
  monster: 'action',
  multiplayer: 'action',
  music: 'casual',
  naval: 'shooting',
  ninja: 'action',
  'ninja-turtle': 'action',
  offroad: 'racing-driving',
  'open-world': 'adventure',
  parking: 'racing-driving',
  parkour: 'platformer',
  piano: 'casual',
  pirates: 'adventure',
  pixel: 'arcade',
  platformer: 'platformer',
  police: 'action',
  pool: 'sports',
  puzzle: 'puzzle',
  racing: 'racing-driving',
  restaurant: 'simulation-idle',
  retro: 'arcade',
  robots: 'action',
  rpg: 'adventure',
  runner: 'skill-hyper-casual',
  scary: 'action',
  scrabble: 'math-word',
  sharks: 'casual',
  shooter: 'shooting',
  simulation: 'simulation-idle',
  skateboard: 'sports',
  'skibidi-toilet': 'action',
  skill: 'skill-hyper-casual',
  snake: 'arcade',
  sniper: 'shooting',
  soccer: 'sports',
  solitaire: 'board-card',
  spinner: 'skill-hyper-casual',
  sports: 'sports',
  stickman: 'action',
  strategy: 'strategy',
  surgery: 'casual',
  survival: 'adventure',
  sword: 'action',
  tanks: 'shooting',
  tap: 'skill-hyper-casual',
  tetris: 'puzzle',
  trivia: 'math-word',
  truck: 'racing-driving',
  'two-player': 'two-player',
  tycoon: 'simulation-idle',
  war: 'action',
  word: 'math-word',
  'world-cup': 'sports',
  worm: 'arcade',
  wrestling: 'sports',
  zombie: 'action',
} as const satisfies Record<string, HubSlug>;

export function hubFor(rawCategory: string): HubSlug | undefined {
  if (!Object.prototype.hasOwnProperty.call(RAW_CATEGORY_TO_HUB, rawCategory)) {
    return undefined;
  }
  return RAW_CATEGORY_TO_HUB[rawCategory as keyof typeof RAW_CATEGORY_TO_HUB];
}
