import type { TileGame } from '@/lib/tile-game';

export const sampleGames: readonly TileGame[] = [
  {
    slug: 'gallery-sample',
    title: 'Sample puzzle',
    cover: '/placeholder-cover.svg',
    hub: 'puzzle',
    publishedAt: '2026-10-01',
    orientation: 'portrait',
    aspect: 1.6,
  },
  {
    slug: 'gallery-racer',
    title: 'Sample racer',
    cover: '/placeholder-cover.svg',
    hub: 'racing-driving',
    publishedAt: '2026-01-01',
    orientation: 'landscape',
    aspect: 1.6,
  },
  {
    slug: 'gallery-missing',
    title: 'Missing cover',
    cover: '/missing-cover.svg',
    hub: 'arcade',
    publishedAt: '2026-10-02',
    orientation: 'all',
    aspect: 0.8,
  },
  {
    slug: 'gallery-match',
    title: 'Sample match',
    cover: '/placeholder-cover.svg',
    hub: 'match-3',
    publishedAt: '2025-06-01',
    orientation: 'portrait',
    aspect: 1,
  },
  {
    slug: 'gallery-sport',
    title: 'Sample sport',
    cover: '/placeholder-cover.svg',
    hub: 'sports',
    publishedAt: '2025-04-01',
    orientation: 'landscape',
    aspect: 1.6,
  },
  {
    slug: 'gallery-word',
    title: 'Sample word',
    cover: '/placeholder-cover.svg',
    hub: 'math-word',
    publishedAt: '2025-03-01',
    orientation: 'portrait',
    aspect: 1.2,
  },
  {
    slug: 'gallery-draw',
    title: 'Sample drawing',
    cover: '/placeholder-cover.svg',
    hub: 'coloring-drawing',
    publishedAt: '2025-02-01',
    orientation: 'landscape',
    aspect: 1.6,
  },
  {
    slug: 'gallery-casual',
    title: 'Sample casual',
    cover: '/placeholder-cover.svg',
    hub: 'casual',
    publishedAt: '2025-01-01',
    orientation: 'all',
    aspect: 1.6,
  },
];
